# Generated by Django 6.0.4 on 2026-04-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precisoram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
